### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nb3rg** [badgerloop-software/mechanical#8]
## Code Issues/Comments/TODO
**Bolded items should take precedence**
Numbering is not indicative of priority.
Wherever reasonable the following should be implemented in a manner that is as robust and interchangeable as possible (i.e. for different motor models, brands, specs, etc.) : 
1. - [ ] Decision on high-level makeup of profile - best time, highest top speed, etc. Base off of rules.
2. - [ ] Output to easily see power lost to internal resistance has heat (I^2R) as well as free run losses MIGHT BE ALL ENCOMPASSED BY FREE RUN LOSSES???
3. - [ ] Add in motor efficiency maps for EMRAX -> likely will encompass a large amount of for loops and if statements as the maps are 2D. Make as a separate function
4. **Output vector/table/matrix for controls:**
     - [ ] a. Time (reference variable)
     - [ ] b. Torque
     - [ ] c. Distances (tape strips too?)
     - [ ] d. Braking T/F (or similar)
     - [ ] e. RPM?
     - [ ] f. Other??? - ask controls team what is useful
5. - [ ] **Need to use continuous torque values instead of peak whenever propulsion runtime>~30 sec.**
6. - [ ] **Figure out idealized profile in regards to kinematics (accel fast, slow, long, short, etc.)**
7. - [x] Double check pack curve in getvoltage.m corresponds to new A123 cells
8. - [ ] Add variable for battery cell instant power output (energy) as heat (internal resistance I^2R) - for EES code
9. - [ ] Add variable for total energy as heat from batteries during run - for EES code
10. - [ ] Add variable for instant power output (energy) as heat from motor (worst case is all as free run losses I BELIEVE, NEED TO DOUBLE CHECK) - for EES code
11. - [ ] Add variable for total power output as heat from motor during run - for EES code
12. - [ ] Look at pulling motor specs from a table/matrix/excel sheet for easy integration/comparison between motors thru run profile
13. - [ ] **Add back in code for gear ratio and wheel diameter for loops (see earlier version on Box)**
14. - [ ] Take into account RPM of different wheels
15. - [ ] Calculation for centripetal force and stress on each wheel (see propulsion design references)
16. - [ ] **Look into friction/interaction of wheel with track**
     - [ ] a. Important to keep in mind being friction limited vs. torque limited. Will likely end up being torque limited due to gear ratios required for long track but might not be the case. 
     - [ ] b. Add in info for friction of wheel (might already be in there)
17. - [x] Update number of cells
18. - [ ] Braking loop should use the pod mass with the equivalent terms added in to calculate the deceleration 
19. - [ ] Vibe environment of pod???
20. - [ ] Add in a variable showing the power dissipated as heat of the motor controller - this may or may not be necessary as there is EES code for extensive thermal calcs on the motor controller. 
21. - [ ] **Linearly ramp initial torque at some rate until it intersects with the continuous torque curve.**
22. - [ ] Clean up "End_mode" to be accurate descriptions.
23. - [ ] **Fix pack voltage vs. time graph by using the relationship for current to torque from emrax datasheet with the constant value rather than a discretized vector in the "get_current" function.**

### NOTES: 
- 0.2-0.4 g's of acceleration likely is sufficient. Just a hunch
- Polyurethane may or may not be sufficient any longer (more centripetal force/ less required friction on longer track)
     - Along with that it may not be necessary given reduced acceleration values
- Have considered reformatting code to be "driven" by electrical requirements. Current>torque>acceleration. Currently is torque>acceleration>current. Max speed governed by current (voltage drop) and pack voltage either way. 

## Non-Code Issues/Comments/TODO
1. (A) I believe it should be further investigated the reasoning behind the use of polyurethane. I think there is a lack of understanding/oversight the has driven the decision to use polyurethane as a wheel coating. I believe it is possible there is sufficient traction via direct aluminum wheel on the track to provide unprohibited acceleration. 
2. (B) Investigate different methods of drivetrain. If gears are desired, consider Forest City Gear

**Comment by nb3rg** [comment]
Example Comment for number 2:
*check box for item 2*
"Completed number 2"

OR if partially completed and stuck/leaving it:
*don't check box for item 2*
"Got stuck trying to get the correct variables to output, seeing odd errors"

**Comment by nb3rg** [comment]
If you remember, detail what numbers were completed in pull requests.
